### ISSUE TITLE
"Event must be of a delegate type" error

### ISSUE THREAD

**Issue by SneakBug8** [AdColony/AdColony-Unity-SDK-3#24]
Error in script.
![2017-07-08 16_54_08-unity 5 5 4f1 personal 64bit - main unity - novel - pc mac linux standalone](https://user-images.githubusercontent.com/11244723/27985959-236b1a56-63ff-11e7-8183-14b6226a27ac.png)

**Comment by cmanibog-ac** [comment]
Our team is currently looking into this. Though, we have not had this reported yet. We will follow up with more information when our tech team is able to investigate further. In the meantime, could I have you check that our setup documentation has been followed at https://github.com/AdColony/AdColony-Unity-SDK-3#installation?

**Comment by akwkong** [comment]
Could you share what your code looks like that assigns the delegate to AdColony.Ads.OnRequestInterstitialFailed?

For an example of how to assign the delegate (though with AdColony.Ads.OnRequestInterstitialFailedWithZone since OnRequestInterstitialFailed is now deprecated), take a look at GameController.cs in ADCUnitySample:
https://github.com/AdColony/AdColony-Unity-SDK-3/blob/master/ADCUnitySample/Assets/Scripts/GameController.cs#L59
