### ISSUE TITLE
Admob Plugins

### ISSUE THREAD

**Issue by kiranmaya** [AdColony/AdColony-Unity-SDK-3#5]
Not working when you imported admob unity plugin,play services resolver and firebase conflicts.

**Comment by IvanMurzak** [comment]
Crashing on Android API 16 at launch

**Comment by cmanibog-ac** [comment]
Our 3.0 Unity plugin is not compatible with the current AdMob adapters available on their Firebase site. Due to re-design on their end in addition to our new API, our Engineers have had to build new adapters. We have sent these adapters to AdMob for certification and are waiting for an update on the status of this process.

**Comment by kiranmaya** [comment]
ok fine, one more question why does it take 45 days to replay?

**Comment by cmanibog-ac** [comment]
My apologies for the delay. We recently opened up the Issues tab for our 3.0 SDKs and our teams have been adjusting to this new channel. We have allowed for more coverage on these GitHub issues, but I also recommend reaching out to our Support team directly by sending a message to support@adcolony.com for efficient communication.

**Comment by smumair06** [comment]
Since, I can see there are many bugs in your plugin. I wanna ask whether should I try adColony or not. As, I don't see any further development on it. Even, you guys are very much slow on replying over such issues.
