### ISSUE TITLE
Failure to initialize! Your hardware does not support this application

### ISSUE THREAD

**Issue by uaprogrammer** [AdColony/AdColony-Unity-SDK-3#8]
On some Android phones game with AdColony can not run. Error message "Failure to initialize! Your hardware does not support this application"
For example on Samsung Galaxy S6/7.
After deleting AdColony SDK - game works normally.

**Comment by cmanibog-ac** [comment]
For further troubleshooting, please open a ticket with our Support team by sending a message to  support@adcolony.com. In the message, send a full console log showing the app activity from when our SDK is initialized through the "Failure to initialize" error.

**Comment by prattpratt** [comment]
I'm observing the same issue. We have several AD networks attached via Mopub adapters. After removing AdColony everything works fine.

**Comment by prattpratt** [comment]
I found the similar issue - https://stackoverflow.com/questions/38529767/unity-android-project-throws-your-hardware-does-not-support-this-application-so . 
Putting this code into android section of `build.gradle` file solves the problem:

    packagingOptions {
        exclude "lib/armeabi/libadcolony.so"
        exclude "lib/armeabi/libjs.so"
        exclude "lib/arm64-v8a/libadcolony.so"
        exclude "lib/arm64-v8a/libjs.so"
        exclude "lib/x86_64/libadcolony.so"
        exclude "lib/x86_64/libjs.so"
    }

**Comment by edencakir** [comment]
Same issue here.

**Comment by Over17** [comment]
This is an issue with Unity: https://issuetracker.unity3d.com/issues/app-failed-to-initialize-your-hardward-does-not-support-this-application-sorry

What happens is that the native libraries for all the architectures are available, including x86-64 (why?) and armv8-64. The armv8-64 libraries end up in the APK.

Now imagine you are running it on a device with 64-bit SoC. The Android OS looks up the native libraries, finds at least one which is armv8-64 and uses it as the primary ABI, loading all libraries from that directory. Unity tries to load libmain.so (the loading proxy) and fails because there are no Unity arm64 libraries available, shows the dialog and shuts down the app.

Unity 2018.1 and later are supporting armv8-64, and also have a proper fix in the build.gradle template (the proper fix is to have abiFilters option in ndk section). Older Unity versions will also be getting a proper fix in the upcoming patch releases.

**Comment by shawnkc** [comment]
Thanks for that update about Unity 2018.1 and subsequent patches. That will be great to have proper architecture filtering, I wonder if this will also be supported with the internal build system (without Gradle).

For those wanting to upgrade quickly, we could release a separate, full-architecture Unity package add-on. I'd rather not release a combined Unity package with all the architectures until Unity fixes it in all the supported Unity versions we support.

We'll keep an eye open for the 2018.1 release.

**Comment by Over17** [comment]
The fixes for the internal build system are also coming (for 2018.1 it may happen in a patch release too - not in the initial release).

Thanks!
